repos:
  - repo: local
    hooks:
      - id: frontend-lint
        name: frontend-lint
        entry: npm run lint --
        language: system
        files: ^src/.*\.(js|jsx)$
        pass_filenames: true
